// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Northwind.API.Tests.Integration.Infrastructure.Services.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CategoryModel
    {
        /// <summary>
        /// Initializes a new instance of the CategoryModel class.
        /// </summary>
        public CategoryModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CategoryModel class.
        /// </summary>
        public CategoryModel(int? categoryId = default(int?), string categoryName = default(string), string description = default(string))
        {
            CategoryId = categoryId;
            CategoryName = categoryName;
            Description = description;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "categoryId")]
        public int? CategoryId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "categoryName")]
        public string CategoryName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

    }
}
