// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Northwind.API.Tests.Integration.Infrastructure.Services.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ProductEditModel
    {
        /// <summary>
        /// Initializes a new instance of the ProductEditModel class.
        /// </summary>
        public ProductEditModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProductEditModel class.
        /// </summary>
        public ProductEditModel(string productName, int? productId = default(int?), int? categoryId = default(int?), int? supplierId = default(int?), string quantityPerUnit = default(string), double? unitPrice = default(double?), int? unitsInStock = default(int?), int? unitsOnOrder = default(int?), int? reorderLevel = default(int?), bool? discontinued = default(bool?))
        {
            ProductId = productId;
            ProductName = productName;
            CategoryId = categoryId;
            SupplierId = supplierId;
            QuantityPerUnit = quantityPerUnit;
            UnitPrice = unitPrice;
            UnitsInStock = unitsInStock;
            UnitsOnOrder = unitsOnOrder;
            ReorderLevel = reorderLevel;
            Discontinued = discontinued;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "productId")]
        public int? ProductId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "productName")]
        public string ProductName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "categoryId")]
        public int? CategoryId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "supplierId")]
        public int? SupplierId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "quantityPerUnit")]
        public string QuantityPerUnit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "unitPrice")]
        public double? UnitPrice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "unitsInStock")]
        public int? UnitsInStock { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "unitsOnOrder")]
        public int? UnitsOnOrder { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "reorderLevel")]
        public int? ReorderLevel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "discontinued")]
        public bool? Discontinued { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (ProductName == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ProductName");
            }
            if (ProductName != null)
            {
                if (ProductName.Length < 4)
                {
                    throw new ValidationException(ValidationRules.MinLength, "ProductName", 4);
                }
            }
            if (UnitPrice != null)
            {
                if (UnitPrice > 2147483647)
                {
                    throw new ValidationException(ValidationRules.InclusiveMaximum, "UnitPrice", 2147483647);
                }
                if (UnitPrice < 0)
                {
                    throw new ValidationException(ValidationRules.InclusiveMinimum, "UnitPrice", 0);
                }
            }
            if (UnitsInStock != null)
            {
                if (UnitsInStock > 2147483647)
                {
                    throw new ValidationException(ValidationRules.InclusiveMaximum, "UnitsInStock", 2147483647);
                }
                if (UnitsInStock < 0)
                {
                    throw new ValidationException(ValidationRules.InclusiveMinimum, "UnitsInStock", 0);
                }
            }
            if (UnitsOnOrder != null)
            {
                if (UnitsOnOrder > 2147483647)
                {
                    throw new ValidationException(ValidationRules.InclusiveMaximum, "UnitsOnOrder", 2147483647);
                }
                if (UnitsOnOrder < 0)
                {
                    throw new ValidationException(ValidationRules.InclusiveMinimum, "UnitsOnOrder", 0);
                }
            }
            if (ReorderLevel != null)
            {
                if (ReorderLevel > 30)
                {
                    throw new ValidationException(ValidationRules.InclusiveMaximum, "ReorderLevel", 30);
                }
                if (ReorderLevel < 0)
                {
                    throw new ValidationException(ValidationRules.InclusiveMinimum, "ReorderLevel", 0);
                }
            }
        }
    }
}
